### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by WobbyChip** [U-M9/U_Releases#1]
var pseudo2addr = util.getPrologue(scanner.scan("8B C1 81 FA ?? ?? ?? ?? 74 ?? 56").Last());

Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at U_Dumper.Program.Main() in C:\Users\WobbyChip\Desktop\U_Releases-main\U_Dumper\Program.cs:line 64

**Comment by U-M9** [comment]
Make sure your Roblox version is up to date
